public enum TokenType {
    // Keywords
    START, FINISH, LOOP, CONDITION, DECLARE, OUTPUT, INPUT,
    FUNCTION, RETURN, BREAK, CONTINUE, ELSE,

    // Literals
    IDENTIFIER, INTEGER, FLOAT, STRING, CHARACTER, BOOLEAN,

    // Operators
    ADD, SUB, MUL, DIV, MOD, EXP,
    EQUAL, NOT_EQUAL, LESS_THAN, LESS_EQUAL, GREATER_THAN, GREATER_EQUAL,
    LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,
    ASSIGN, ADD_ASSIGN, SUB_ASSIGN, MUL_ASSIGN, DIV_ASSIGN,
    INC, DEC,

    // Punctuators
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    LEFT_BRACKET, RIGHT_BRACKET, COMMA, SEMICOLON, COLON,

    // Special
    COMMENT, WHITESPACE, EOF, ERROR
}
